import type { Program } from './cms-types'

/**
 * Fallback programs rendered by `/api/public/cms` when Firestore is
 * unreachable or when the `programs` collection is empty. Directly
 * reflects the authentic educational tracks from EPath's official curriculum
 * documents (Edmentum International, Cambridge ESOL, FabLab EIU).
 *
 * Locale-aware VI/EN strings are included so the site is consistent
 * in either locale until the admin publishes overrides via
 * `/admin/programs`.
 */
export const DEFAULT_PROGRAMS: Program[] = [
  // =========================================================================
  // KINDERGARTEN (MẦM NON)
  // =========================================================================
  {
    id: 'default-program-kindy-speedup',
    slug: 'kindy-speedup-english',
    level: 'kindergarten',
    title: {
      vi: 'Tiếng Anh Bứt phá – Mầm non',
      en: 'SpeedUp English – Kindergarten',
    },
    shortDescription: {
      vi: 'Phát triển tiếng Anh như ngôn ngữ thứ hai (ESL) theo giáo trình Cambridge University Press và chuẩn CLIL.',
      en: 'US-aligned ESL on official Cambridge University Press curriculum and CLIL methodology for ages 3–6.',
    },
    content: {
      vi: '<p>Chương trình Tiếng Anh Bứt Phá tại EPath Education được xây dựng theo hệ thống giáo trình chính thức của Cambridge University Press, phát triển tiếng Anh như một ngôn ngữ thứ hai (ESL). Nội dung: ESL chuẩn Mỹ · Topic-based Learning · CLIL · Early Literacy · Early Mathematics theo chuẩn US Core Standards · Nghe – Nói, phát âm và vốn từ vựng.</p><p>EPath sử dụng kết quả khảo thí Cambridge làm căn cứ xác định năng lực, xếp lớp và theo dõi sự tiến bộ khách quan của trẻ.</p>',
      en: '<p>SpeedUp English is built on official Cambridge University Press curriculum developing English as a Second Language. Content: US ESL · Topic-based Learning · CLIL · Early Literacy · Early Mathematics (US Core Standards) · Listening, Speaking, Pronunciation, and Vocabulary.</p><p>EPath uses Cambridge Assessment English outcomes to determine learner level, placement, and progress.</p>',
    },
    ageRange: '3 – 6 tuổi',
    objectives: [
      { vi: 'Hình thành nền tảng tiếng Anh tự nhiên như ngôn ngữ thứ hai', en: 'Develop English naturally as a second language' },
      { vi: 'Làm quen Early Literacy và Toán tư duy cơ bản bằng tiếng Anh', en: 'Early Literacy & foundational Math in English' },
      { vi: 'Hình thành phản xạ nghe nói và tự tin giao tiếp trong môi trường song ngữ', en: 'Natural conversational reflexes in bilingual environments' },
    ],
    highlights: [
      { vi: 'Giáo trình Cambridge University Press chính thức', en: 'Official Cambridge University Press curriculum' },
      { vi: 'Phương pháp tích hợp ngôn ngữ & nội dung CLIL', en: 'CLIL content & language integrated methodology' },
      { vi: 'Đánh giá khách quan theo khung Cambridge English', en: 'Objective Cambridge English benchmarking' },
    ],
    imageUrl: '/images/programs/program-kindy.jpg',
    ctaLabel: undefined,
    ctaUrl: '/admissions?program=kindergarten',
    order: 0,
    isActive: true,
    status: 'PUBLISHED',
    rejectionReason: '',
    scheduledAt: '',
    publishedAt: '',
    createdByUid: '',
    createdByEmail: '',
    createdByName: '',
    lastReviewerUid: '',
    lastReviewerEmail: '',
    lastReviewerName: '',
    submittedAt: '',
    reviewedAt: '',
  },
  {
    id: 'default-program-kindy-foundation',
    slug: 'kindy-academic-foundation',
    level: 'kindergarten',
    title: {
      vi: 'Nền tảng Học thuật Quốc tế – Mầm non',
      en: 'Academic Foundation – Kindergarten',
    },
    shortDescription: {
      vi: 'Xây dựng nền tảng tiền học thuật: Letter Sounds, Phonics, Blending Sounds, Toán và STEM bằng tiếng Anh.',
      en: 'Pre-academic foundations: Letter Sounds, Phonics, Blending Sounds, Math and STEM exploration in English.',
    },
    content: {
      vi: '<p>Chương trình tập trung xây dựng nền tảng tiền học thuật: Letter Sounds và Phonics để hiểu mối liên hệ chữ cái – âm thanh · Luyện Blending Sounds ghép âm và đánh vần từ đơn giản (CVC) đến phức tạp · Đọc viết nền tảng theo chuẩn học thuật · Khái niệm Toán học bằng tiếng Anh (số đếm, phép tính, hình khối, đo lường, tư duy logic) · Hoạt động STEM khám phá, đặt câu hỏi và thử nghiệm.</p><p>Giúp trẻ sẵn sàng học các môn học bằng tiếng Anh ở bậc Tiểu học song ngữ hoặc quốc tế.</p>',
      en: '<p>Develops pre-academic foundations: Letter Sounds & Phonics for letter-sound correspondence · Blending Sounds practice from simple CVC to complex structures · Academic early literacy · Math concepts in English · Hands-on STEM exploration and questioning.</p>',
    },
    ageRange: '4 – 6 tuổi',
    objectives: [
      { vi: 'Phonics & Blending Sounds đọc - đánh vần chuẩn xác', en: 'Accurate Phonics & sound blending skills' },
      { vi: 'Làm quen Toán học và tư duy logic bằng tiếng Anh', en: 'Foundational mathematics & logic in English' },
      { vi: 'Khám phá Khoa học & STEM thông qua thực nghiệm', en: 'Hands-on Science & STEM experimentation' },
    ],
    highlights: [
      { vi: 'Mô hình chuyển tiếp từ "học tiếng Anh" sang "học bằng tiếng Anh"', en: 'Transition from learning English to learning in English' },
      { vi: 'Nền tảng vững vàng trước khi vào lớp 1 Song ngữ/Quốc tế', en: 'Solid springboard for Grade 1 bilingual/international school' },
      { vi: 'Tích hợp STEM thực hành kích thích trí tò mò khoa học', en: 'Hands-on STEM sparking scientific curiosity' },
    ],
    imageUrl: '/images/programs/program-kindy.jpg',
    ctaLabel: undefined,
    ctaUrl: '/admissions?program=kindergarten',
    order: 1,
    isActive: true,
    status: 'PUBLISHED',
    rejectionReason: '',
    scheduledAt: '',
    publishedAt: '',
    createdByUid: '',
    createdByEmail: '',
    createdByName: '',
    lastReviewerUid: '',
    lastReviewerEmail: '',
    lastReviewerName: '',
    submittedAt: '',
    reviewedAt: '',
  },

  // =========================================================================
  // ELEMENTARY (TIỂU HỌC)
  // =========================================================================
  {
    id: 'default-program-elementary-speedup',
    slug: 'elementary-speedup-english',
    level: 'elementary',
    title: {
      vi: 'Tiếng Anh Bứt phá – Tiểu học',
      en: 'SpeedUp English – Elementary',
    },
    shortDescription: {
      vi: 'Phát triển toàn diện 4 kỹ năng theo khung Cambridge (Starters, Movers, Flyers) kết hợp CLIL và học qua dự án.',
      en: 'Comprehensive 4 skills development aligned with Cambridge (Starters, Movers, Flyers) with CLIL and project-based learning.',
    },
    content: {
      vi: '<p>Chương trình chuyển trọng tâm từ giao tiếp sang sử dụng tiếng Anh trong học thuật. Phát triển 4 kỹ năng Nghe – Nói – Đọc – Viết bám sát chuẩn Cambridge English Qualifications · Mở rộng vốn từ vựng học thuật và ngữ pháp nâng cao · CLIL tích hợp Toán, Khoa học và Xã hội · Project-based Learning rèn luyện kỹ năng thuyết trình, làm việc nhóm và tư duy độc lập.</p>',
      en: '<p>Transitions from conversational fluency to academic English literacy. Comprehensive 4 skills aligned with Cambridge Qualifications · Expanded academic vocabulary and advanced grammar · CLIL integrating Math, Science, and Social Studies · Project-based learning fostering presentations and teamwork.</p>',
    },
    ageRange: '7 – 12 tuổi (Lớp 1 – 5)',
    objectives: [
      { vi: 'Chinh phục chứng chỉ Cambridge Starters, Movers, Flyers', en: 'Achieve Cambridge Starters, Movers, Flyers certifications' },
      { vi: 'Sử dụng tiếng Anh như công cụ tiếp thu tri thức đa môn', en: 'Use English as a multidisciplinary learning instrument' },
      { vi: 'Kỹ năng thuyết trình, làm việc nhóm và dự án học tập', en: 'Presentation, teamwork, and project skills' },
    ],
    highlights: [
      { vi: 'Hệ thống khảo thí Cambridge Assessment English', en: 'Cambridge Assessment English testing system' },
      { vi: 'Phương pháp Project-based Learning hiện đại', en: 'Modern Project-based Learning methodology' },
      { vi: 'Tiếp cận tiếng Anh học thuật tự nhiên qua môn học', en: 'Natural academic English acquisition via subjects' },
    ],
    imageUrl: '/images/programs/program-elementary.jpg',
    ctaLabel: undefined,
    ctaUrl: '/admissions?program=elementary',
    order: 2,
    isActive: true,
    status: 'PUBLISHED',
    rejectionReason: '',
    scheduledAt: '',
    publishedAt: '',
    createdByUid: '',
    createdByEmail: '',
    createdByName: '',
    lastReviewerUid: '',
    lastReviewerEmail: '',
    lastReviewerName: '',
    submittedAt: '',
    reviewedAt: '',
  },
  {
    id: 'default-program-elementary-foundation',
    slug: 'elementary-foundation-base',
    level: 'elementary',
    title: {
      vi: 'Tiểu học Tiêu chuẩn – Foundation Track',
      en: 'Elementary Foundation Track',
    },
    shortDescription: {
      vi: 'Xây dựng kiến thức học thuật cốt lõi ELA, Math, Science với 5 giờ học tương tác/tuần cùng 50% GV Quốc tế + 50% GV Song ngữ.',
      en: 'Core academic foundations in ELA, Math, and Science with 5 interactive hours/week (50% International + 50% Bilingual teachers).',
    },
    content: {
      vi: '<p><strong>Lớp 1–2 (5 giờ/tuần):</strong> Học 2 môn ELA (Ngữ văn Anh) + Mathematics (Toán học). Gồm 2 buổi Online 60 phút và 2 buổi Onsite 90 phút.</p><p><strong>Lớp 3–5 (5 giờ/tuần):</strong> Học 3 môn ELA + Mathematics + Science (Khoa học). Gồm 2 buổi Online 60 phút và 2 buổi Onsite 90 phút (Science 45 phút + ELA 45 phút; ELA 60 phút + Tutor phụ đạo 30 phút).</p><p><strong>Đội ngũ giáo viên:</strong> 50% Giáo viên Nước ngoài (chuyên môn Elementary Education) + 50% Giáo viên Song ngữ (IELTS 7.0+).</p><p><strong>Học liệu:</strong> Cấp tài khoản học tập Edmentum thời hạn 12 tháng.</p>',
      en: '<p><strong>Grades 1–2 (5 hrs/week):</strong> ELA + Math with 2 Online 60-min and 2 Onsite 90-min sessions.</p><p><strong>Grades 3–5 (5 hrs/week):</strong> ELA + Math + Science with blended Online and Onsite classes.</p><p><strong>Faculty:</strong> 50% International Teachers + 50% Bilingual Teachers (IELTS 7.0+).</p><p><strong>Curriculum:</strong> 12-month Edmentum digital learning portal.</p>',
    },
    ageRange: 'Lớp 1 – 5',
    objectives: [
      { vi: 'Thành thạo ELA, Toán học và Khoa học bằng tiếng Anh', en: 'Mastery of ELA, Mathematics, and Science in English' },
      { vi: 'Xây dựng năng lực học tập tự chủ và tư duy phản biện', en: 'Build independent learning and critical thinking' },
      { vi: 'Duy trì học bạ xuất sắc tại trường chính khóa Việt Nam', en: 'Maintain stellar performance at Vietnamese home school' },
    ],
    highlights: [
      { vi: '50% GV Quốc tế + 50% GV Song ngữ IELTS 7.0+', en: '50% International + 50% Bilingual (IELTS 7.0+)' },
      { vi: 'Tài khoản Edmentum International 12 tháng', en: '12-month Edmentum International digital access' },
      { vi: 'Thời lượng tối ưu 5 giờ/tuần không gây quá tải', en: 'Optimized 5 hrs/week avoiding study overload' },
    ],
    imageUrl: '/images/programs/program-elementary.jpg',
    ctaLabel: undefined,
    ctaUrl: '/admissions?program=elementary',
    order: 3,
    isActive: true,
    status: 'PUBLISHED',
    rejectionReason: '',
    scheduledAt: '',
    publishedAt: '',
    createdByUid: '',
    createdByEmail: '',
    createdByName: '',
    lastReviewerUid: '',
    lastReviewerEmail: '',
    lastReviewerName: '',
    submittedAt: '',
    reviewedAt: '',
  },
  {
    id: 'default-program-elementary-advanced',
    slug: 'elementary-advanced-prime',
    level: 'elementary',
    title: {
      vi: 'Tiểu học Quốc tế – U.S. Academic Program',
      en: 'Elementary U.S. Academic Program',
    },
    shortDescription: {
      vi: 'Chương trình chính khóa chuẩn phổ thông Mỹ Calvert/Edmentum với đầy đủ 4 môn: Math, ELA, Science, Social Studies.',
      en: 'Official US elementary curriculum (Calvert/Edmentum) with full core subjects: Math, ELA, Science, Social Studies.',
    },
    content: {
      vi: '<p>Chương trình dành cho học sinh có nền tảng học thuật tốt, muốn tiếp cận trọn vẹn chương trình Tiểu học Mỹ như một học sinh bản xứ. Bao gồm 4 môn bắt buộc: Toán (Math), Ngôn ngữ (ELA), Khoa học (Science) và Khoa học Xã hội (Social Studies) cùng các môn tự chọn (Elective).</p><p>Mô hình Blended Learning kết hợp tự học trên nền tảng Edmentum (12 tháng) cùng các lớp giảng dạy trực tiếp từ GV Quốc tế & Song ngữ và Cố vấn học tập (Academic Advisor) kèm 1:1.</p><p>Trang bị năng lực tương đương trường quốc tế với mức học phí chỉ bằng 1/3.</p>',
      en: '<p>Comprehensive US elementary curriculum for students aiming for bilingual or international transition. Covers all 4 core disciplines: Math, ELA, Science, and Social Studies plus electives.</p><p>Blended learning model on Edmentum with dedicated 1:1 Academic Advisor support at one-third the cost of traditional international schools.</p>',
    },
    ageRange: 'Lớp 3 – 5',
    objectives: [
      { vi: 'Tiếp cận toàn diện 4 môn chính khóa Tiểu học chuẩn Hoa Kỳ', en: 'Full 4-subject US elementary core curriculum' },
      { vi: 'Được phân công Cố vấn học tập (Academic Advisor) đồng hành 1:1', en: 'Dedicated 1:1 Academic Advisor mentorship' },
      { vi: 'Năng lực tương đương học sinh quốc tế với chi phí tối ưu 1/3', en: 'International school equivalent competency at 1/3 tuition' },
    ],
    highlights: [
      { vi: 'Học liệu số hóa chuẩn Mỹ Calvert Learning & Edmentum', en: 'Calvert Learning & Edmentum US digital curriculum' },
      { vi: 'Academic Advisor kèm 1:1 bù đắp lỗ hổng kiến thức', en: '1:1 Academic Advisor personalized tutoring' },
      { vi: 'Chứng nhận hoàn thành cấp lớp từ tổ chức giáo dục Mỹ', en: 'US grade-level completion recognition' },
    ],
    imageUrl: '/images/programs/program-elementary.jpg',
    ctaLabel: undefined,
    ctaUrl: '/admissions?program=elementary',
    order: 4,
    isActive: true,
    status: 'PUBLISHED',
    rejectionReason: '',
    scheduledAt: '',
    publishedAt: '',
    createdByUid: '',
    createdByEmail: '',
    createdByName: '',
    lastReviewerUid: '',
    lastReviewerEmail: '',
    lastReviewerName: '',
    submittedAt: '',
    reviewedAt: '',
  },

  // =========================================================================
  // MIDDLE SCHOOL (THCS)
  // =========================================================================
  {
    id: 'default-program-middle-speedup',
    slug: 'middle-speedup-english',
    level: 'middle',
    title: {
      vi: 'Tiếng Anh Bứt phá – THCS (IELTS Academic)',
      en: 'SpeedUp English – Middle School (IELTS Track)',
    },
    shortDescription: {
      vi: 'Chinh phục IELTS Band 5.5 – 6.5+, phát triển tư duy phản biện, kỹ năng tranh biện và viết luận học thuật.',
      en: 'Target IELTS 5.5 – 6.5+, critical thinking, academic essay writing, and competitive debate skills.',
    },
    content: {
      vi: '<p>Chương trình tập trung hoàn thiện năng lực tiếng Anh học thuật và luyện thi IELTS Academic. Phát triển 4 kỹ năng Nghe – Nói – Đọc – Viết chuyên sâu, từ vựng học thuật (Academic Word List), ngữ pháp nâng cao. Rèn luyện kỹ năng viết luận (Essay Writing), thuyết trình, tranh biện (Debate) và tư duy phản biện (Critical Thinking).</p><p>Mục tiêu đạt IELTS Band 5.5+ vào cuối lớp 8 - điều kiện tiên quyết để bước vào giai đoạn tích lũy tín chỉ THPT Hoa Kỳ.</p>',
      en: '<p>Focused academic English and IELTS Academic preparation. Intensive training in all 4 skills, academic lexicon, advanced syntax, essay writing, public debate, and analytical thinking.</p><p>Prepares students to achieve IELTS 5.5+ by Grade 8, the prerequisite for official US high school credit accumulation.</p>',
    },
    ageRange: '13 – 16 tuổi (Lớp 6 – 8)',
    objectives: [
      { vi: 'Đạt IELTS Academic Band 5.5 – 6.5+ trước khi kết thúc lớp 8', en: 'Achieve IELTS 5.5 – 6.5+ before completing Grade 8' },
      { vi: 'Thành thạo kỹ năng viết luận học thuật và tranh biện', en: 'Academic essay writing and public debate fluency' },
      { vi: 'Sẵn sàng tiếp cận giáo trình phổ thông Mỹ ở bậc THPT', en: 'Ready for US high school curriculum tracks' },
    ],
    highlights: [
      { vi: 'Chiến lược làm bài thi IELTS Academic chuẩn quốc tế', en: 'Standardized IELTS Academic test-taking strategies' },
      { vi: 'Phát triển tư duy phản biện và nghiên cứu độc lập', en: 'Critical thinking & independent research skills' },
      { vi: 'Điều kiện tiên quyết cho lộ trình Song bằng Quốc tế', en: 'Prerequisite milestone for Dual Diploma pathways' },
    ],
    imageUrl: '/images/programs/program-middle.jpg',
    ctaLabel: undefined,
    ctaUrl: '/admissions?program=middle',
    order: 5,
    isActive: true,
    status: 'PUBLISHED',
    rejectionReason: '',
    scheduledAt: '',
    publishedAt: '',
    createdByUid: '',
    createdByEmail: '',
    createdByName: '',
    lastReviewerUid: '',
    lastReviewerEmail: '',
    lastReviewerName: '',
    submittedAt: '',
    reviewedAt: '',
  },
  {
    id: 'default-program-middle-foundation',
    slug: 'middle-academic-foundation',
    level: 'middle',
    title: {
      vi: 'Nền tảng Học thuật Quốc tế – THCS',
      en: 'Academic Foundation – Middle School',
    },
    shortDescription: {
      vi: 'Chuyển từ "học bằng tiếng Anh" sang "tư duy và nghiên cứu độc lập", học 4 môn ELA, Math, Science, Social Studies.',
      en: 'Shift from "learning in English" to "independent thinking & research" across ELA, Math, Science, and Social Studies.',
    },
    content: {
      vi: '<p>Dành cho học sinh THCS đang theo chương trình Việt Nam muốn nâng cao Academic English và kiến thức học thuật đa môn. Thời lượng 5–6 giờ/tuần với 4 môn: ELA, Math, Science, Social Studies.</p><p>Hè năm lớp 8, học sinh được trải nghiệm học thử 1 tín chỉ quan trọng (Math hoặc Science) để nhà trường và phụ huynh đánh giá năng lực thực tế, làm căn cứ lựa chọn lộ trình Song bằng Việt – Mỹ hoặc Tú tài Mỹ toàn thời gian ở bậc THPT.</p>',
      en: '<p>Designed for middle schoolers pursuing Vietnamese curriculum while advancing academic English in core disciplines: ELA, Math, Science, Social Studies (5–6 hrs/wk).</p><p>In summer of Grade 8, students trial an official credit course to assess readiness for Dual Diploma or Fulltime US Diploma tracks.</p>',
    },
    ageRange: 'Lớp 6 – 8',
    objectives: [
      { vi: 'Làm chủ kiến thức cốt lõi 4 môn THCS theo chuẩn Hoa Kỳ', en: 'Master 4 core middle school disciplines to US standards' },
      { vi: 'Trải nghiệm học thử tín chỉ Mỹ thật vào hè năm lớp 8', en: 'Trial an official US credit course in summer Grade 8' },
      { vi: 'Xác định định hướng phân luồng chuẩn xác cho bậc THPT', en: 'Determine high school academic pathway with confidence' },
    ],
    highlights: [
      { vi: '50% GV Nước Ngoài (Secondary Education) + 50% GV Song ngữ', en: '50% International + 50% Bilingual Secondary Teachers' },
      { vi: 'Lộ trình chuyển tiếp mượt mà vào chương trình Song bằng', en: 'Seamless transition into high school Dual Diploma' },
      { vi: 'Tích lũy tư duy nghiên cứu và phản biện đa chiều', en: 'Multidimensional critical inquiry and research mindset' },
    ],
    imageUrl: '/images/programs/program-middle.jpg',
    ctaLabel: undefined,
    ctaUrl: '/admissions?program=middle',
    order: 6,
    isActive: true,
    status: 'PUBLISHED',
    rejectionReason: '',
    scheduledAt: '',
    publishedAt: '',
    createdByUid: '',
    createdByEmail: '',
    createdByName: '',
    lastReviewerUid: '',
    lastReviewerEmail: '',
    lastReviewerName: '',
    submittedAt: '',
    reviewedAt: '',
  },
  {
    id: 'default-program-middle-us-curriculum',
    slug: 'middle-us-curriculum',
    level: 'middle',
    title: {
      vi: 'Chương trình Trung học Mỹ – US Middle School Pathway',
      en: 'US Middle School Pathway',
    },
    shortDescription: {
      vi: 'Học sinh chính thức của trường trực tuyến EdOptions Academy, đăng ký học và tích lũy tín chỉ vào Tú tài Mỹ.',
      en: 'Official EdOptions Academy enrollment, accumulating accredited credits toward the US High School Diploma.',
    },
    content: {
      vi: '<p>Học sinh chính thức trở thành học sinh của Trường trực tuyến EdOptions Academy (Edmentum International). Học sinh được học theo tín chỉ với toàn bộ nội dung chính khóa (Math, Science) theo chuẩn Mỹ. Nếu hoàn thành đạt từ 80% trở lên, các tín chỉ này sẽ được tính điểm chính thức và tích lũy vào tổng 21.5 tín chỉ cần có để nhận bằng Tú tài Mỹ (U.S. Diploma) ở cấp 3.</p><p>Lộ trình hướng đến IELTS 6.0 vào cuối lớp 7 và tạo tiền đề tốt nghiệp THPT Mỹ sớm.</p>',
      en: '<p>Students enroll as official students of EdOptions Academy (Edmentum), taking accredited Math and Science courses that count toward the 21.5 credits required for the US High School Diploma.</p>',
    },
    ageRange: 'Lớp 6 – 8',
    objectives: [
      { vi: 'Tích lũy sớm tín chỉ chuẩn Mỹ trước khi bước vào lớp 9', en: 'Earn early US high school credits before Grade 9' },
      { vi: 'Đạt IELTS 6.0 và năng lực học tập độc lập theo chuẩn Mỹ', en: 'Achieve IELTS 6.0 and independent US study habits' },
      { vi: 'Sở hữu bảng điểm chính thức từ trường kiểm định Cognia & WASC', en: 'Official transcripts from Cognia & WASC accredited school' },
    ],
    highlights: [
      { vi: 'Tín chỉ được công nhận chính thức vào bằng Tú tài Mỹ', en: 'Official credits transferred to US High School Diploma' },
      { vi: 'EdOptions Academy – trường K-12 trực tuyến hàng đầu Hoa Kỳ', en: 'EdOptions Academy premier accredited US online school' },
      { vi: 'Mở rộng cơ hội tốt nghiệp THPT Mỹ sớm hơn thời hạn', en: 'Enables potential early high school graduation' },
    ],
    imageUrl: '/images/programs/program-middle.jpg',
    ctaLabel: undefined,
    ctaUrl: '/admissions?program=middle',
    order: 7,
    isActive: true,
    status: 'PUBLISHED',
    rejectionReason: '',
    scheduledAt: '',
    publishedAt: '',
    createdByUid: '',
    createdByEmail: '',
    createdByName: '',
    lastReviewerUid: '',
    lastReviewerEmail: '',
    lastReviewerName: '',
    submittedAt: '',
    reviewedAt: '',
  },

  // =========================================================================
  // HIGH SCHOOL (THPT)
  // =========================================================================
  {
    id: 'default-program-high-dual',
    slug: 'high-dual-diploma',
    level: 'high',
    title: {
      vi: 'Dual Diploma — Song bằng THPT Việt Nam & Hoa Kỳ',
      en: 'Dual Diploma — Vietnam & US High School Dual Diploma',
    },
    shortDescription: {
      vi: '1.1 Lựa chọn Dual Diploma (Song bằng) — Học sinh theo học đồng thời chương trình THPT tại Việt Nam và chương trình THPT Hoa Kỳ thông qua EdOptions Academy để nhận 2 bằng tốt nghiệp.',
      en: '1.1 Dual Diploma Option — Study concurrently in Vietnam and US curriculum via EdOptions Academy to earn both high school diplomas.',
    },
    content: {
      vi: '<p>Lộ trình học tập lý tưởng cho học sinh vừa hoàn thành trọn vẹn chương trình THPT Việt Nam, vừa tích lũy 5.0 tín chỉ chuẩn Mỹ và 1.0 tín chỉ nâng cao AP® qua EdOptions Academy. Các môn học quốc tế được bố trí chủ yếu vào kỳ hè và linh hoạt trong năm học để không làm gián đoạn việc học chính khóa trong nước.</p><p><strong>Bằng cấp đạt được:</strong> Bằng tốt nghiệp THPT Việt Nam + Bằng Tú tài Mỹ (U.S. High School Diploma) kiểm định bởi Cognia & WASC + Chứng chỉ IELTS 7.0+ và chứng nhận môn AP của College Board.</p><p>Mở rộng cánh cửa vào các đại học quốc tế tại Việt Nam (nhận học bổng cao) và xét tuyển thẳng vào các trường đại học hàng đầu thế giới.</p>',
      en: '<p>Concurrent pathway earning both Vietnamese High School Diploma and Cognia & WASC accredited U.S. High School Diploma via EdOptions Academy. Coursework arranged during summer terms and flexible evening hours (5 standard credits + 1 AP credit).</p><p>Includes IELTS 7.0+ preparation and College Board AP® credits for maximum global university admissions advantages.</p>',
    },
    ageRange: '15 – 18 tuổi (Lớp 9 – 12)',
    objectives: [
      { vi: 'Nhận đồng thời 2 bằng tốt nghiệp THPT Việt Nam và Tú tài Mỹ', en: 'Earn dual Vietnamese & US High School Diplomas' },
      { vi: 'Tích lũy tín chỉ nâng cao AP® được công nhận tại đại học thế giới', en: 'Earn College Board approved AP® university-level credits' },
      { vi: 'Chinh phục chứng chỉ IELTS Academic 7.0+', en: 'Achieve IELTS Academic 7.0+' },
    ],
    highlights: [
      { vi: '1.1 Lựa chọn Dual Diploma (Song bằng)', en: '1.1 Dual Diploma Pathway' },
      { vi: 'Bằng tốt nghiệp U.S. High School Diploma kiểm định Cognia & WASC', en: 'Cognia & WASC accredited U.S. High School Diploma' },
      { vi: 'Lịch học linh hoạt, không làm gián đoạn học chính khóa', en: 'Flexible schedule without local school disruption' },
    ],
    imageUrl: '/images/programs/program-dual-diploma.jpg',
    ctaLabel: undefined,
    ctaUrl: '/admissions?program=high',
    order: 8,
    isActive: true,
    status: 'PUBLISHED',
    rejectionReason: '',
    scheduledAt: '',
    publishedAt: '',
    createdByUid: '',
    createdByEmail: '',
    createdByName: '',
    lastReviewerUid: '',
    lastReviewerEmail: '',
    lastReviewerName: '',
    submittedAt: '',
    reviewedAt: '',
  },
  {
    id: 'default-program-high-fulltime',
    slug: 'high-fulltime-homeschool',
    level: 'high',
    title: {
      vi: 'Fulltime Homeschool — Học toàn thời gian chương trình THPT Hoa Kỳ',
      en: 'Fulltime Homeschool — Full-Time US High School Diploma',
    },
    shortDescription: {
      vi: '1.2 Lựa chọn Fulltime Homeschool (Homeschool toàn phần) — Học toàn thời gian 100% chương trình THPT Hoa Kỳ qua EdOptions Academy, tích lũy 21.5 tín chỉ và tốt nghiệp như học sinh bản xứ.',
      en: '1.2 Fulltime Homeschool Option — 100% full-time US High School curriculum via EdOptions Academy, earning 21.5 credits.',
    },
    content: {
      vi: '<p>Dành cho học sinh đã xác định mục tiêu du học hoặc ứng tuyển các trường đại học top đầu thế giới có mức độ cạnh tranh cao. Học sinh học tập toàn thời gian theo đúng khung chương trình của trường trung học Hoa Kỳ thông qua EdOptions Academy.</p><p>Học sinh tích lũy đầy đủ 21.5 tín chỉ chuẩn Mỹ (bao gồm ELA, Math, Science, Social Studies, Ngoại ngữ, Nghệ thuật và Tự chọn). Học sinh có thể tốt nghiệp sớm hơn thời hạn nếu đẩy nhanh tiến độ hoàn thành tín chỉ.</p><p>Kết hợp ôn luyện chuyên sâu SAT/ACT và các môn AP®, được các trường đại học công nhận như một học sinh bản địa Mỹ – lợi thế vượt trội so với diện học sinh quốc tế thông thường.</p>',
      en: '<p>Comprehensive full-time US high school education via EdOptions Academy. Students earn all 21.5 credits according to US graduation requirements, including AP® courses and SAT/ACT prep.</p><p>Graduates apply to global universities with the status of native US high school graduates, dramatically elevating admission competitiveness.</p>',
    },
    ageRange: '15 – 18 tuổi (Lớp 9 – 12)',
    objectives: [
      { vi: 'Tốt nghiệp với Bằng Tú tài Mỹ chính quy như học sinh bản địa', en: 'Graduate with official US Diploma with native status' },
      { vi: 'Hoàn thành 21.5 tín chỉ chuẩn Hoa Kỳ và các môn nâng cao AP®', en: 'Complete 21.5 US credits and College Board AP® courses' },
      { vi: 'Cơ hội tốt nghiệp sớm để nộp hồ sơ sớm vào ĐH danh tiếng', en: 'Opportunity for early graduation and early university application' },
    ],
    highlights: [
      { vi: '1.2 Lựa chọn Fulltime Homeschool (Homeschool toàn phần)', en: '1.2 Fulltime Homeschool Pathway' },
      { vi: 'Được các đại học xét tuyển như học sinh bản xứ Hoa Kỳ', en: 'Evaluated by universities with US native applicant status' },
      { vi: 'Tích lũy 21.5 tín chỉ chuẩn Mỹ và các môn nâng cao AP®', en: 'Complete 21.5 US credits and College Board AP® courses' },
    ],
    imageUrl: '/images/programs/program-high.jpg',
    ctaLabel: undefined,
    ctaUrl: '/admissions?program=high',
    order: 9,
    isActive: true,
    status: 'PUBLISHED',
    rejectionReason: '',
    scheduledAt: '',
    publishedAt: '',
    createdByUid: '',
    createdByEmail: '',
    createdByName: '',
    lastReviewerUid: '',
    lastReviewerEmail: '',
    lastReviewerName: '',
    submittedAt: '',
    reviewedAt: '',
  },
  {
    id: 'default-program-high-portfolio',
    slug: 'high-personal-development',
    level: 'high',
    title: {
      vi: 'Phát triển Năng lực Cá nhân – Beyond the Classroom',
      en: 'Beyond the Classroom Portfolio',
    },
    shortDescription: {
      vi: 'Khóa học kỹ năng thế kỷ 21, dự án sáng tạo STEAM FabLab EIU, tranh biện và đấu trường học thuật quốc tế (IMEC, STEMCO, TIMO).',
      en: '21st-century skills, STEAM maker projects at FabLab EIU, debate, and international Olympiads (IMEC, STEMCO, TIMO).',
    },
    content: {
      vi: '<p>Bên cạnh học thuật, EPath xây dựng hệ sinh thái trải nghiệm thực tế nhằm phát triển toàn diện student profile: Giao lưu học thuật cùng doanh nghiệp và chuyên gia · Tham gia đấu trường học thuật quốc tế IMEC, STEMCO, GMEC, TIMO · Thực hành công nghệ Robotics & STEM Maker tại FabLab EIU · Dự án cá nhân và nhóm rèn luyện Critical Thinking, Research Skills, Public Speaking, Leadership và Community Service.</p><p>Các thành tích này trực tiếp hoàn thiện Academic Portfolio chuẩn quốc tế để nộp hồ sơ du học và săn học bổng.</p>',
      en: '<p>Holistic student development ecosystem beyond standard academics: Academic Olympiads (IMEC, STEMCO, GMEC, TIMO) · STEAM Maker engineering at FabLab EIU · Real-world leadership, debate, community service projects building an elite Academic Portfolio.</p>',
    },
    ageRange: 'Lớp 6 – 12',
    objectives: [
      { vi: 'Xây dựng Academic Portfolio (Hồ sơ học thuật cá nhân) nổi bật', en: 'Build an exceptional personal Academic Portfolio' },
      { vi: 'Rèn luyện 5 kỹ năng then chốt: Phản biện, Nghiên cứu, Thuyết trình, Lãnh đạo, Hoạt động xã hội', en: 'Master Critical Thinking, Research, Public Speaking, Leadership, Community Service' },
      { vi: 'Thử thách tại các kỳ thi Olympic Toán & STEM quốc tế', en: 'Compete in prestigious international Math & STEM Olympiads' },
    ],
    highlights: [
      { vi: 'Trải nghiệm công nghệ thực tiễn tại FabLab EIU', en: 'Hands-on tech innovation at FabLab EIU' },
      { vi: 'Tích lũy huy chương và chứng nhận tại các sân chơi quốc tế', en: 'Medals and credentials from international arenas' },
      { vi: 'Xây dựng hồ sơ cá nhân tạo lợi thế cạnh tranh tuyển sinh', en: 'Distinctive student profile for top university admissions' },
    ],
    imageUrl: '/images/programs/program-high.jpg',
    ctaLabel: undefined,
    ctaUrl: '/admissions?program=high',
    order: 10,
    isActive: true,
    status: 'PUBLISHED',
    rejectionReason: '',
    scheduledAt: '',
    publishedAt: '',
    createdByUid: '',
    createdByEmail: '',
    createdByName: '',
    lastReviewerUid: '',
    lastReviewerEmail: '',
    lastReviewerName: '',
    submittedAt: '',
    reviewedAt: '',
  },
  {
    id: 'default-program-high-counseling',
    slug: 'high-international-counseling',
    level: 'high',
    title: {
      vi: 'Cố vấn Lộ trình Học tập Quốc tế – Academic Counseling',
      en: 'International Academic Counseling',
    },
    shortDescription: {
      vi: 'Dịch vụ cố vấn giáo dục cá nhân hóa 1:1, đánh giá năng lực định kỳ, định hướng chiến lược tín chỉ và săn học bổng du học.',
      en: 'Personalized 1:1 academic advising, periodic diagnostic assessments, credit strategy, and university scholarship counseling.',
    },
    content: {
      vi: '<p>Mỗi học sinh có năng lực, sở thích và mục tiêu khác nhau. EPath cung cấp dịch vụ Cố vấn Lộ trình Học tập Quốc tế 1 kèm 1, đồng hành xuyên suốt cùng học sinh và phụ huynh: Đánh giá năng lực học thuật theo chuẩn quốc tế · Hoạch định lộ trình từng năm học · Lựa chọn môn học và môn AP phù hợp năng lực · Quản lý tiến độ học tập và tháo gỡ khó khăn · Xây dựng chiến lược hồ sơ ứng tuyển đại học và học bổng du học tại Mỹ, Canada, Úc, Châu Âu.</p>',
      en: '<p>Personalized 1:1 academic advising guiding families through goal setting, diagnostic benchmarking, curriculum selection, AP credit planning, and strategic college admissions portfolios for top global universities.</p>',
    },
    ageRange: 'Mầm non – Lớp 12',
    objectives: [
      { vi: 'Định hình lộ trình học tập cá nhân hóa phù hợp tối đa tiềm năng', en: 'Personalized pathway customized to student potential' },
      { vi: 'Theo dõi tiến độ học thuật và điều chỉnh định kỳ cùng phụ huynh', en: 'Continuous academic monitoring and parent alignment' },
      { vi: 'Tối ưu hóa cơ hội học bổng và đỗ vào các đại học top đầu', en: 'Maximize scholarship and admission success at top universities' },
    ],
    highlights: [
      { vi: 'Cố vấn học thuật (Academic Advisor) chuyên môn cao đồng hành 1:1', en: 'Dedicated expert Academic Advisor 1:1 guidance' },
      { vi: 'Đại diện và bảo vệ quyền lợi học tập của học sinh', en: 'Advocating and safeguarding student academic interests' },
      { vi: 'Hỗ trợ săn học bổng du học Mỹ, Canada, Úc và châu Âu', en: 'Scholarship guidance for US, Canada, Australia, and Europe' },
    ],
    imageUrl: '/images/programs/program-high.jpg',
    ctaLabel: undefined,
    ctaUrl: '/admissions?program=high',
    order: 11,
    isActive: true,
    status: 'PUBLISHED',
    rejectionReason: '',
    scheduledAt: '',
    publishedAt: '',
    createdByUid: '',
    createdByEmail: '',
    createdByName: '',
    lastReviewerUid: '',
    lastReviewerEmail: '',
    lastReviewerName: '',
    submittedAt: '',
    reviewedAt: '',
  },
]
