import type { Program } from './cms-types'

/**
 * Fallback programs rendered by `/api/public/cms` when Firestore is
 * unreachable or when the `programs` collection is empty. Mirrors the
 * brochure "Chương trình đào tạo" section so the public site still
 * shows realistic content even before an admin has seeded data.
 *
 * Locale-aware VI/EN strings are included so the site is consistent
 * in either locale until the admin publishes overrides via
 * `/admin/programs`.
 */
export const DEFAULT_PROGRAMS = [
  // ----- Kindergarten -----
  {
    id: 'default-program-kindy-speedup',
    slug: 'kindy-speedup-english',
    level: 'kindergarten',
    title: {
      vi: 'Tiếng Anh Bứt phá – Mầm non',
      en: 'SpeedUp English – Kindergarten',
    },
    shortDescription: {
      vi: 'ESL chuẩn Mỹ theo khung Cambridge English Qualifications, dành cho 3–6 tuổi.',
      en: 'US-aligned ESL on the Cambridge English Qualifications framework, ages 3–6.',
    },
    content: {
      vi: '<p>Chương trình Tiếng Anh Bứt Phá tại EPath Education được xây dựng theo hệ thống giáo trình Cambridge University Press. Nội dung: ESL chuẩn Mỹ · Topic-based Learning · CLIL · Early Literacy · Early Mathematics (US Core Standards) · Nghe – Nói – phát âm – từ vựng.</p><p>EPath sử dụng đánh giá và chứng chỉ của Hội đồng Khảo thí Cambridge làm căn cứ xác định năng lực, xếp lớp và đánh giá kết quả.</p>',
      en: '<p>The SpeedUp English programme is built on the Cambridge University Press curriculum. Content: US ESL · Topic-based Learning · CLIL · Early Literacy · Early Mathematics (US Core Standards) · Listening – Speaking – Pronunciation – Vocabulary.</p><p>EPath uses Cambridge Assessment English outcomes to determine learner level, placement and progress.</p>',
    },
    ageRange: '3 – 6 tuổi',
    objectives: [
      { vi: 'Hình thành nền tảng tiếng Anh như ngôn ngữ thứ hai', en: 'Build English as a Second Language' },
      { vi: 'Giao tiếp tự nhiên', en: 'Natural communication' },
    ],
    highlights: [
      { vi: 'Giáo trình Cambridge chính thức', en: 'Official Cambridge curriculum' },
      { vi: 'CLIL · Early Literacy', en: 'CLIL · Early Literacy' },
    ],
    imageUrl: '',
    ctaLabel: undefined,
    ctaUrl: '/contact',
    order: 0,
    isActive: true,
    status: 'PUBLISHED',
    rejectionReason: '',
    scheduledAt: '',
    publishedAt: '',
    createdByUid: '',
    createdByEmail: '',
    createdByName: '',
    lastReviewerUid: '',
    lastReviewerEmail: '',
    lastReviewerName: '',
    submittedAt: '',
    reviewedAt: '',
  },
  {
    id: 'default-program-kindy-foundation',
    slug: 'kindy-academic-foundation',
    level: 'kindergarten',
    title: {
      vi: 'Nền tảng Học thuật Quốc tế – Mầm non',
      en: 'Academic Foundation – Kindergarten',
    },
    shortDescription: {
      vi: 'Phonics, Toán và STEM bằng tiếng Anh, dành cho 4–6 tuổi.',
      en: 'Phonics, English-medium Math and STEM for ages 4–6.',
    },
    content: {
      vi: '<p>Letter Sounds · Phonics · Blending Sounds · Đọc – viết nền tảng theo chuẩn học thuật · Toán bằng tiếng Anh (số đếm, phép tính, hình học, đo lường, logic) · STEM quan sát – đặt câu hỏi – thử nghiệm.</p>',
      en: '<p>Letter Sounds · Phonics · Blending Sounds · Foundational reading & writing · English-medium Math (counting, operations, geometry, measurement, logic) · STEM (observe – question – experiment).</p>',
    },
    ageRange: '4 – 6 tuổi',
    objectives: [
      { vi: 'Đọc – viết tiếng Anh nền tảng', en: 'Foundational English reading & writing' },
      { vi: 'Khám phá STEM', en: 'Explore STEM' },
    ],
    highlights: [],
    imageUrl: '',
    ctaLabel: undefined,
    ctaUrl: '/contact',
    order: 1,
    isActive: true,
    status: 'PUBLISHED',
    rejectionReason: '',
    scheduledAt: '',
    publishedAt: '',
    createdByUid: '',
    createdByEmail: '',
    createdByName: '',
    lastReviewerUid: '',
    lastReviewerEmail: '',
    lastReviewerName: '',
    submittedAt: '',
    reviewedAt: '',
  },

  // ----- Elementary -----
  {
    id: 'default-program-elementary-foundation',
    slug: 'elementary-foundation-base',
    level: 'elementary',
    title: {
      vi: 'Tiểu học Tiêu chuẩn – Foundation Track',
      en: 'Elementary Foundation Track',
    },
    shortDescription: {
      vi: 'Chương trình Tiểu học Tiêu chuẩn với 5 giờ tương tác mỗi tuần.',
      en: 'Standard Elementary programme with 5 interactive hours per week.',
    },
    content: {
      vi: '<p><strong>Lớp 2 trở xuống (5 giờ/tuần)</strong> – ELA + Math · 2 buổi Online 60 phút (Math – GV Nước Ngoài; ELA – GV Song ngữ) · 2 buổi Onsite 90 phút (ELA + Math).</p><p><strong>Lớp 3 trở lên (5 giờ/tuần)</strong> – ELA + Math + Science · 2 buổi Online · 2 buổi Onsite (Science 45 + ELA 45; ELA 60 + Tutor 30).</p><p><strong>Giáo viên:</strong> 50% International + 50% Bilingual (IELTS 7.0+).</p>',
      en: '<p><strong>Grades 1–2 (5 hrs/week)</strong> – ELA + Math · 2 Online 60-min · 2 Onsite 90-min.</p><p><strong>Grades 3+ (5 hrs/week)</strong> – ELA + Math + Science · 2 Online · 2 Onsite.</p><p><strong>Teachers:</strong> 50% International + 50% Bilingual (IELTS 7.0+).</p>',
    },
    ageRange: 'Lớp 1 – 5',
    objectives: [
      { vi: 'Nền tảng tiếng Anh học thuật', en: 'Academic English foundations' },
      { vi: 'Tư duy Toán & Khoa học', en: 'Math & Science thinking' },
    ],
    highlights: [
      { vi: 'Tài khoản Edmentum 12 tháng', en: '12-month Edmentum account' },
    ],
    imageUrl: '',
    ctaLabel: undefined,
    ctaUrl: '/contact',
    order: 2,
    isActive: true,
    status: 'PUBLISHED',
    rejectionReason: '',
    scheduledAt: '',
    publishedAt: '',
    createdByUid: '',
    createdByEmail: '',
    createdByName: '',
    lastReviewerUid: '',
    lastReviewerEmail: '',
    lastReviewerName: '',
    submittedAt: '',
    reviewedAt: '',
  },
  {
    id: 'default-program-elementary-advanced',
    slug: 'elementary-advanced-prime',
    level: 'elementary',
    title: {
      vi: 'Tiểu học Quốc tế – Advanced Track',
      en: 'Elementary Advanced Track',
    },
    shortDescription: {
      vi: 'Áp dụng từ KS2A (Year 3). 6.5 – 7 giờ tương tác mỗi tuần.',
      en: 'For KS2A (Year 3+) with 6.5 – 7 interactive hours per week.',
    },
    content: {
      vi: '<p><strong>Lớp 3 + 4 (6.5 giờ/tuần)</strong> – ELA + Math + Social Studies + Science.</p><p><strong>Lớp 5+ (7 giờ/tuần)</strong> – tăng cường Social Studies.</p>',
      en: '<p><strong>Grades 3–4 (6.5 hrs/week)</strong> – ELA + Math + Social Studies + Science.</p><p><strong>Grade 5+ (7 hrs/week)</strong> with extended Social Studies.</p>',
    },
    ageRange: 'Lớp 3 – 5',
    objectives: [
      { vi: 'Sẵn sàng chương trình Song ngữ / Quốc tế', en: 'Ready for Bilingual / International tracks' },
    ],
    highlights: [],
    imageUrl: '',
    ctaLabel: undefined,
    ctaUrl: '/contact',
    order: 3,
    isActive: true,
    status: 'PUBLISHED',
    rejectionReason: '',
    scheduledAt: '',
    publishedAt: '',
    createdByUid: '',
    createdByEmail: '',
    createdByName: '',
    lastReviewerUid: '',
    lastReviewerEmail: '',
    lastReviewerName: '',
    submittedAt: '',
    reviewedAt: '',
  },

  // ----- Middle School -----
  {
    id: 'default-program-middle-foundation',
    slug: 'middle-academic-foundation',
    level: 'middle',
    title: {
      vi: 'Nền tảng Học thuật Quốc tế – THCS',
      en: 'Academic Foundation – Middle School',
    },
    shortDescription: {
      vi: 'Từ "học bằng tiếng Anh" đến "tư duy và học tập độc lập bằng tiếng Anh".',
      en: 'From "learning in English" to "thinking and studying independently in English".',
    },
    content: {
      vi: '<p><strong>Mục tiêu:</strong> Học sinh THCS muốn nâng cao Academic English & kiến thức học thuật. Định hướng IELTS 5.5+ và Dual Diploma.</p><p>ELA · Math · Science · Social Studies · 5–6 giờ/tuần.</p>',
      en: '<p><strong>Goal:</strong> Advanced Academic English & content. Target IELTS 5.5+ and Dual Diploma readiness.</p><p>ELA · Math · Science · Social Studies · 5–6 hrs/week.</p>',
    },
    ageRange: '13 – 16 tuổi',
    objectives: [
      { vi: 'IELTS 5.5+', en: 'IELTS 5.5+' },
      { vi: 'Sẵn sàng Dual Diploma / chương trình Mỹ', en: 'Ready for Dual Diploma / US programmes' },
    ],
    highlights: [],
    imageUrl: '',
    ctaLabel: undefined,
    ctaUrl: '/contact',
    order: 4,
    isActive: true,
    status: 'PUBLISHED',
    rejectionReason: '',
    scheduledAt: '',
    publishedAt: '',
    createdByUid: '',
    createdByEmail: '',
    createdByName: '',
    lastReviewerUid: '',
    lastReviewerEmail: '',
    lastReviewerName: '',
    submittedAt: '',
    reviewedAt: '',
  },
  {
    id: 'default-program-middle-speedup',
    slug: 'middle-speedup-english',
    level: 'middle',
    title: {
      vi: 'Tiếng Anh Bứt phá – THCS',
      en: 'SpeedUp English – Middle School',
    },
    shortDescription: {
      vi: 'IELTS preparation · Critical thinking · Research skills.',
      en: 'IELTS preparation · Critical thinking · Research skills.',
    },
    content: {
      vi: '<p>Bốn kỹ năng chuẩn IELTS · Từ vựng học thuật · Ngữ pháp nâng cao · Viết luận – thuyết trình – tranh biện.</p>',
      en: '<p>Four skills at IELTS standard · Academic vocabulary · Advanced grammar · Essay writing – presentations – debate.</p>',
    },
    ageRange: '13 – 16 tuổi',
    objectives: [
      { vi: 'IELTS 5.5 – 6.5+', en: 'IELTS 5.5 – 6.5+' },
    ],
    highlights: [],
    imageUrl: '',
    ctaLabel: undefined,
    ctaUrl: '/contact',
    order: 5,
    isActive: true,
    status: 'PUBLISHED',
    rejectionReason: '',
    scheduledAt: '',
    publishedAt: '',
    createdByUid: '',
    createdByEmail: '',
    createdByName: '',
    lastReviewerUid: '',
    lastReviewerEmail: '',
    lastReviewerName: '',
    submittedAt: '',
    reviewedAt: '',
  },

  // ----- High School -----
  {
    id: 'default-program-high-dual',
    slug: 'high-dual-diploma',
    level: 'high',
    title: {
      vi: 'US Dual High School Diploma – Song bằng',
      en: 'US Dual High School Diploma',
    },
    shortDescription: {
      vi: 'Nhận đồng thời bằng THPT Việt Nam và bằng THPT Hoa Kỳ qua EdOptions Academy.',
      en: 'Earn both Vietnamese & US High School Diplomas via EdOptions Academy.',
    },
    content: {
      vi: '<p>Học sinh theo học đồng thời chương trình THPT Việt Nam và chương trình THPT Hoa Kỳ. Tốt nghiệp em nhận cả <strong>Bằng THPT Việt Nam</strong> và <strong>Bằng THPT Hoa Kỳ</strong>.</p>',
      en: '<p>Students earn both <strong>the Vietnamese High School Diploma</strong> and <strong>the US High School Diploma</strong> simultaneously via EdOptions Academy.</p>',
    },
    ageRange: '15 – 18 tuổi',
    objectives: [
      { vi: 'Song bằng Việt – Mỹ', en: 'Vietnamese & US diplomas' },
      { vi: 'Hồ sơ du học & đại học quốc tế', en: 'Study-abroad & international portfolio' },
    ],
    highlights: [
      { vi: 'EdOptions Academy (Edmentum)', en: 'EdOptions Academy (Edmentum)' },
    ],
    imageUrl: '',
    ctaLabel: undefined,
    ctaUrl: '/contact',
    order: 6,
    isActive: true,
    status: 'PUBLISHED',
    rejectionReason: '',
    scheduledAt: '',
    publishedAt: '',
    createdByUid: '',
    createdByEmail: '',
    createdByName: '',
    lastReviewerUid: '',
    lastReviewerEmail: '',
    lastReviewerName: '',
    submittedAt: '',
    reviewedAt: '',
  },
  {
    id: 'default-program-high-fulltime',
    slug: 'high-fulltime-homeschool',
    level: 'high',
    title: {
      vi: 'US High School Diploma – Fulltime Homeschool',
      en: 'US High School Diploma – Fulltime Homeschool',
    },
    shortDescription: {
      vi: 'Chương trình Tú tài Mỹ toàn thời gian qua EdOptions Academy.',
      en: 'Fulltime US High School Diploma via EdOptions Academy.',
    },
    content: {
      vi: '<p>Học sinh học tập, tích lũy tín chỉ và hoàn thành yêu cầu tốt nghiệp hoàn toàn theo chương trình EdOptions Academy. Toàn bộ nội dung, đánh giá và quản lý tiến độ theo tiêu chuẩn Hoa Kỳ.</p>',
      en: '<p>Students earn credits and graduate entirely through EdOptions Academy, following US education standards end-to-end.</p>',
    },
    ageRange: '15 – 18 tuổi',
    objectives: [
      { vi: 'Tốt nghiệp THPT Hoa Kỳ', en: 'Graduate with a US High School Diploma' },
    ],
    highlights: [
      { vi: 'Học 100% trực tuyến', en: '100% online' },
    ],
    imageUrl: '',
    ctaLabel: undefined,
    ctaUrl: '/contact',
    order: 7,
    isActive: true,
    status: 'PUBLISHED',
    rejectionReason: '',
    scheduledAt: '',
    publishedAt: '',
    createdByUid: '',
    createdByEmail: '',
    createdByName: '',
    lastReviewerUid: '',
    lastReviewerEmail: '',
    lastReviewerName: '',
    submittedAt: '',
    reviewedAt: '',
  },
]
